def get_gexp_schema():
    return [
        {'name': 'ParticipantBarcode',
         'type': 'STRING'},
        {'name': 'SampleBarcode',
         'type': 'STRING'},
        {'name': 'AliquotBarcode',
         'type': 'STRING'},
        {'name': 'Study',
         'type': 'INTEGER'},
        {'name': 'SampleTypeLetterCode',
         'type': 'STRING'},
        {'name': 'Platform',
         'type': 'STRING'},
        {'name': 'Pipeline',
         'type': 'STRING'},
        {'name': 'Gene_Name',
         'type': 'STRING'},
        {'name': 'Long_Gene_Name',
         'type': 'STRING'},
        {'name': 'Count',
         'type': 'FLOAT'}
    ]

def get_protein_schema():
    return [
        {'name': 'ParticipantBarcode',
         'type': 'STRING'},
        {'name': 'SampleBarcode',
         'type': 'STRING'},
        {'name': 'AliquotBarcode',
         'type': 'STRING'},
        {'name': 'Study',
         'type': 'INTEGER'},
        {'name': 'SampleTypeLetterCode',
         'type': 'STRING'},
        {'name': 'Platform',
         'type': 'STRING'},
        {'name': 'Pipeline',
         'type': 'STRING'},
        {'name': 'Gene_Name',
         'type': 'STRING'},
        {'name': 'Protein_Name',
         'type': 'STRING'},
        {'name': 'Protein_Expression',
         'type': 'FLOAT'}
    ]

def get_mirna_schema():
    return [
        {'name': 'ParticipantBarcode',
         'type': 'STRING'},
        {'name': 'SampleBarcode',
         'type': 'STRING'},
        {'name': 'AliquotBarcode',
         'type': 'STRING'},
        {'name': 'Study',
         'type': 'INTEGER'},
        {'name': 'SampleTypeLetterCode',
         'type': 'STRING'},
        {'name': 'Platform',
         'type': 'STRING'},
        {'name': 'Pipeline',
         'type': 'STRING'},
        {'name': 'miRNA_ID',
         'type': 'STRING'},
        {'name': 'read_per_million',
         'type': 'FLOAT'},
        {'name': 'read_count',
         'type': 'INTEGER'}
    ]

def get_meth_schema():
    return [
        {'name': 'ParticipantBarcode',
         'type': 'STRING'},
        {'name': 'SampleBarcode',
         'type': 'STRING'},
        {'name': 'AliquotBarcode',
         'type': 'STRING'},
        {'name': 'Study',
         'type': 'INTEGER'},
        {'name': 'SampleTypeLetterCode',
         'type': 'STRING'},
        {'name': 'Platform',
         'type': 'STRING'},
        {'name': 'Probe_ID',
         'type': 'STRING'},
        {'name': 'Beta_Value',
         'type': 'FLOAT'}
    ]

def get_user_gen_schema():
    return [
        {'name': 'SampleBarcode',
         'type': 'STRING'},
        {'name': 'Project',
         'type': 'INTEGER'},
        {'name': 'Study',
         'type': 'INTEGER'}
    ]